- include: "level-1/1.1.1.1.yml"
  when: "'1.1.1.1' not in cis_level_1_exclusions"
- include: "level-1/1.1.1.3.yml"
  when: "'1.1.1.3' not in cis_level_1_exclusions"
- include: "level-1/1.1.12.yml"
  when: "'1.1.12' not in cis_level_1_exclusions"
- include: "level-1/1.1.13.yml"
  when: "'1.1.13' not in cis_level_1_exclusions"
- include: "level-1/1.1.14.yml"
  when: "'1.1.14' not in cis_level_1_exclusions"
- include: "level-1/1.1.18.yml"
  when: "'1.1.18' not in cis_level_1_exclusions"
- include: "level-1/1.1.2.yml"
  when: "'1.1.2' not in cis_level_1_exclusions"
- include: "level-1/1.1.25.yml"
  when: "'1.1.25' not in cis_level_1_exclusions"
- include: "level-1/1.1.27.yml"
  when: "'1.1.27' not in cis_level_1_exclusions"
- include: "level-1/1.1.3.yml"
  when: "'1.1.3' not in cis_level_1_exclusions"
- include: "level-1/1.1.4.yml"
  when: "'1.1.4' not in cis_level_1_exclusions"
- include: "level-1/1.1.5.yml"
  when: "'1.1.5' not in cis_level_1_exclusions"
- include: "level-1/1.1.6.yml"
  when: "'1.1.6' not in cis_level_1_exclusions"
- include: "level-1/1.1.7.yml"
  when: "'1.1.7' not in cis_level_1_exclusions"
- include: "level-1/1.1.8.yml"
  when: "'1.1.8' not in cis_level_1_exclusions"
- include: "level-1/1.1.9.yml"
  when: "'1.1.9' not in cis_level_1_exclusions"
- include: "level-1/1.2.1.yml"
  when: "'1.2.1' not in cis_level_1_exclusions"
- include: "level-1/1.2.2.yml"
  when: "'1.2.2' not in cis_level_1_exclusions"
- include: "level-1/1.2.3.yml"
  when: "'1.2.3' not in cis_level_1_exclusions"
- include: "level-1/1.3.1.yml"
  when: "'1.3.1' not in cis_level_1_exclusions"
- include: "level-1/1.3.2.yml"
  when: "'1.3.2' not in cis_level_1_exclusions"
- include: "level-1/1.4.2.yml"
  when: "'1.4.2' not in cis_level_1_exclusions"
- include: "level-1/1.4.3.yml"
  when: "'1.4.3' not in cis_level_1_exclusions"
- include: "level-1/1.5.1.yml"
  when: "'1.5.1' not in cis_level_1_exclusions"
- include: "level-1/1.5.2.yml"
  when: "'1.5.2' not in cis_level_1_exclusions"
- include: "level-1/1.5.3.yml"
  when: "'1.5.3' not in cis_level_1_exclusions"
- include: "level-1/1.5.4.yml"
  when: "'1.5.4' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.1.yml"
  when: "'1.6.1.1' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.2.yml"
  when: "'1.6.1.2' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.3.yml"
  when: "'1.6.1.3' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.4.yml"
  when: "'1.6.1.4' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.6.yml"
  when: "'1.6.1.6' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.7.yml"
  when: "'1.6.1.7' not in cis_level_1_exclusions"
- include: "level-1/1.6.1.8.yml"
  when: "'1.6.1.8' not in cis_level_1_exclusions"
- include: "level-1/1.7.1.yml"
  when: "'1.7.1' not in cis_level_1_exclusions"
- include: "level-1/1.7.2.yml"
  when: "'1.7.2' not in cis_level_1_exclusions"
- include: "level-1/1.7.4.yml"
  when: "'1.7.4' not in cis_level_1_exclusions"
- include: "level-1/1.7.5.yml"
  when: "'1.7.5' not in cis_level_1_exclusions"
- include: "level-1/1.7.6.yml"
  when: "'1.7.6' not in cis_level_1_exclusions"
- include: "level-1/1.9.yml"
  when: "'1.9' not in cis_level_1_exclusions"
- include: "level-1/2.2.1.1.yml"
  when: "'2.2.1.1' not in cis_level_1_exclusions"
- include: "level-1/2.2.1.2.yml"
  when: "'2.2.1.2' not in cis_level_1_exclusions"
- include: "level-1/2.2.1.3.yml"
  when: "'2.2.1.3' not in cis_level_1_exclusions"
- include: "level-1/2.2.10.yml"
  when: "'2.2.10' not in cis_level_1_exclusions"
- include: "level-1/2.2.11.yml"
  when: "'2.2.11' not in cis_level_1_exclusions"
- include: "level-1/2.2.12.yml"
  when: "'2.2.12' not in cis_level_1_exclusions"
- include: "level-1/2.2.13.yml"
  when: "'2.2.13' not in cis_level_1_exclusions"
- include: "level-1/2.2.14.yml"
  when: "'2.2.14' not in cis_level_1_exclusions"
- include: "level-1/2.2.15.yml"
  when: "'2.2.15' not in cis_level_1_exclusions"
- include: "level-1/2.2.16.yml"
  when: "'2.2.16' not in cis_level_1_exclusions"
- include: "level-1/2.2.17.yml"
  when: "'2.2.17' not in cis_level_1_exclusions"
- include: "level-1/2.2.19.yml"
  when: "'2.2.19' not in cis_level_1_exclusions"
- include: "level-1/2.2.2.yml"
  when: "'2.2.2' not in cis_level_1_exclusions"
- include: "level-1/2.2.3.yml"
  when: "'2.2.3' not in cis_level_1_exclusions"
- include: "level-1/2.2.4.yml"
  when: "'2.2.4' not in cis_level_1_exclusions"
- include: "level-1/2.2.5.yml"
  when: "'2.2.5' not in cis_level_1_exclusions"
- include: "level-1/2.2.6.yml"
  when: "'2.2.6' not in cis_level_1_exclusions"
- include: "level-1/2.2.7.yml"
  when: "'2.2.7' not in cis_level_1_exclusions"
- include: "level-1/2.2.8.yml"
  when: "'2.2.8' not in cis_level_1_exclusions"
- include: "level-1/2.2.9.yml"
  when: "'2.2.9' not in cis_level_1_exclusions"
- include: "level-1/2.3.1.yml"
  when: "'2.3.1' not in cis_level_1_exclusions"
- include: "level-1/2.3.2.yml"
  when: "'2.3.2' not in cis_level_1_exclusions"
- include: "level-1/2.3.3.yml"
  when: "'2.3.3' not in cis_level_1_exclusions"
- include: "level-1/2.3.4.yml"
  when: "'2.3.4' not in cis_level_1_exclusions"
- include: "level-1/2.3.5.yml"
  when: "'2.3.5' not in cis_level_1_exclusions"
- include: "level-1/3.2.1.yml"
  when: "'3.2.1' not in cis_level_1_exclusions"
- include: "level-1/3.2.2.yml"
  when: "'3.2.2' not in cis_level_1_exclusions"
- include: "level-1/3.3.1.yml"
  when: "'3.3.1' not in cis_level_1_exclusions"
- include: "level-1/3.3.10.yml"
  when: "'3.3.10' not in cis_level_1_exclusions"
- include: "level-1/3.3.2.yml"
  when: "'3.3.2' not in cis_level_1_exclusions"
- include: "level-1/3.3.4.yml"
  when: "'3.3.4' not in cis_level_1_exclusions"
- include: "level-1/3.3.5.yml"
  when: "'3.3.5' not in cis_level_1_exclusions"
- include: "level-1/3.3.6.yml"
  when: "'3.3.6' not in cis_level_1_exclusions"
- include: "level-1/3.3.7.yml"
  when: "'3.3.7' not in cis_level_1_exclusions"
- include: "level-1/3.3.8.yml"
  when: "'3.3.8' not in cis_level_1_exclusions"
- include: "level-1/3.3.9.yml"
  when: "'3.3.9' not in cis_level_1_exclusions"
- include: "level-1/4.2.1.1.yml"
  when: "'4.2.1.1' not in cis_level_1_exclusions"
- include: "level-1/4.2.1.2.yml"
  when: "'4.2.1.2' not in cis_level_1_exclusions"
- include: "level-1/4.2.1.3.yml"
  when: "'4.2.1.3' not in cis_level_1_exclusions"
- include: "level-1/4.2.1.5.yml"
  when: "'4.2.1.5' not in cis_level_1_exclusions"
- include: "level-1/4.2.1.6.yml"
  when: "'4.2.1.6' not in cis_level_1_exclusions"
- include: "level-1/5.1.1.yml"
  when: "'5.1.1' not in cis_level_1_exclusions"
- include: "level-1/5.1.2.yml"
  when: "'5.1.2' not in cis_level_1_exclusions"
- include: "level-1/5.1.3.yml"
  when: "'5.1.3' not in cis_level_1_exclusions"
- include: "level-1/5.1.4.yml"
  when: "'5.1.4' not in cis_level_1_exclusions"
- include: "level-1/5.1.5.yml"
  when: "'5.1.5' not in cis_level_1_exclusions"
- include: "level-1/5.1.6.yml"
  when: "'5.1.6' not in cis_level_1_exclusions"
- include: "level-1/5.1.7.yml"
  when: "'5.1.7' not in cis_level_1_exclusions"
- include: "level-1/5.1.8.yml"
  when: "'5.1.8' not in cis_level_1_exclusions"
- include: "level-1/5.3.10.yml"
  when: "'5.3.10' not in cis_level_1_exclusions"
- include: "level-1/5.3.11.yml"
  when: "'5.3.11' not in cis_level_1_exclusions"
- include: "level-1/5.3.12.yml"
  when: "'5.3.12' not in cis_level_1_exclusions"
- include: "level-1/5.3.13.yml"
  when: "'5.3.13' not in cis_level_1_exclusions"
- include: "level-1/5.3.14.yml"
  when: "'5.3.14' not in cis_level_1_exclusions"
- include: "level-1/5.3.15.yml"
  when: "'5.3.15' not in cis_level_1_exclusions"
- include: "level-1/5.3.17.yml"
  when: "'5.3.17' not in cis_level_1_exclusions"
- include: "level-1/5.3.18.yml"
  when: "'5.3.18' not in cis_level_1_exclusions"
- include: "level-1/5.3.19.yml"
  when: "'5.3.19' not in cis_level_1_exclusions"
- include: "level-1/5.3.20.yml"
  when: "'5.3.20' not in cis_level_1_exclusions"
- include: "level-1/5.3.21.yml"
  when: "'5.3.21' not in cis_level_1_exclusions"
- include: "level-1/5.3.3.yml"
  when: "'5.3.3' not in cis_level_1_exclusions"
- include: "level-1/5.3.4.yml"
  when: "'5.3.4' not in cis_level_1_exclusions"
- include: "level-1/5.3.5.yml"
  when: "'5.3.5' not in cis_level_1_exclusions"
- include: "level-1/5.3.6.yml"
  when: "'5.3.6' not in cis_level_1_exclusions"
- include: "level-1/5.3.7.yml"
  when: "'5.3.7' not in cis_level_1_exclusions"
- include: "level-1/5.3.9.yml"
  when: "'5.3.9' not in cis_level_1_exclusions"
- include: "level-1/5.4.1.yml"
  when: "'5.4.1' not in cis_level_1_exclusions"
- include: "level-1/5.4.2.yml"
  when: "'5.4.2' not in cis_level_1_exclusions"
- include: "level-1/5.4.3.yml"
  when: "'5.4.3' not in cis_level_1_exclusions"
- include: "level-1/5.4.4.yml"
  when: "'5.4.4' not in cis_level_1_exclusions"
- include: "level-1/5.5.1.1.yml"
  when: "'5.5.1.1' not in cis_level_1_exclusions"
- include: "level-1/5.5.1.2.yml"
  when: "'5.5.1.2' not in cis_level_1_exclusions"
- include: "level-1/5.5.1.3.yml"
  when: "'5.5.1.3' not in cis_level_1_exclusions"
- include: "level-1/5.5.1.4.yml"
  when: "'5.5.1.4' not in cis_level_1_exclusions"
- include: "level-1/5.5.1.5.yml"
  when: "'5.5.1.5' not in cis_level_1_exclusions"
- include: "level-1/5.5.2.yml"
  when: "'5.5.2' not in cis_level_1_exclusions"
- include: "level-1/5.5.3.yml"
  when: "'5.5.3' not in cis_level_1_exclusions"
- include: "level-1/5.5.4.yml"
  when: "'5.5.4' not in cis_level_1_exclusions"
- include: "level-1/5.7.yml"
  when: "'5.7' not in cis_level_1_exclusions"
- include: "level-1/6.1.10.yml"
  when: "'6.1.10' not in cis_level_1_exclusions"
- include: "level-1/6.1.11.yml"
  when: "'6.1.11' not in cis_level_1_exclusions"
- include: "level-1/6.1.12.yml"
  when: "'6.1.12' not in cis_level_1_exclusions"
- include: "level-1/6.1.13.yml"
  when: "'6.1.13' not in cis_level_1_exclusions"
- include: "level-1/6.1.14.yml"
  when: "'6.1.14' not in cis_level_1_exclusions"
- include: "level-1/6.1.2.yml"
  when: "'6.1.2' not in cis_level_1_exclusions"
- include: "level-1/6.1.3.yml"
  when: "'6.1.3' not in cis_level_1_exclusions"
- include: "level-1/6.1.4.yml"
  when: "'6.1.4' not in cis_level_1_exclusions"
- include: "level-1/6.1.5.yml"
  when: "'6.1.5' not in cis_level_1_exclusions"
- include: "level-1/6.1.6.yml"
  when: "'6.1.6' not in cis_level_1_exclusions"
- include: "level-1/6.1.7.yml"
  when: "'6.1.7' not in cis_level_1_exclusions"
- include: "level-1/6.1.8.yml"
  when: "'6.1.8' not in cis_level_1_exclusions"
- include: "level-1/6.1.9.yml"
  when: "'6.1.9' not in cis_level_1_exclusions"
- include: "level-1/6.2.2.yml"
  when: "'6.2.2' not in cis_level_1_exclusions"
- include: "level-1/6.2.3.yml"
  when: "'6.2.3' not in cis_level_1_exclusions"
- include: "level-1/6.2.4.yml"
  when: "'6.2.4' not in cis_level_1_exclusions"
- include: "level-1/6.2.5.yml"
  when: "'6.2.5' not in cis_level_1_exclusions"
- include: "level-1/6.2.6.yml"
  when: "'6.2.6' not in cis_level_1_exclusions"
- include: "level-1/6.2.7.yml"
  when: "'6.2.7' not in cis_level_1_exclusions"
- include: "level-1/6.2.8.yml"
  when: "'6.2.8' not in cis_level_1_exclusions"
- include: "level-1/6.2.9.yml"
  when: "'6.2.9' not in cis_level_1_exclusions"
- include: "level-1/6.2.10.yml"
  when: "'6.2.10' not in cis_level_1_exclusions"
- include: "level-1/6.2.11.yml"
  when: "'6.2.11' not in cis_level_1_exclusions"
- include: "level-1/6.2.12.yml"
  when: "'6.2.12' not in cis_level_1_exclusions"
- include: "level-1/6.2.13.yml"
  when: "'6.2.13' not in cis_level_1_exclusions"
- include: "level-1/6.2.14.yml"
  when: "'6.2.14' not in cis_level_1_exclusions"
- include: "level-1/6.2.15.yml"
  when: "'6.2.15' not in cis_level_1_exclusions"
- include: "level-1/6.2.16.yml"
  when: "'6.2.16' not in cis_level_1_exclusions"
- include: "level-1/6.2.17.yml"
  when: "'6.2.17' not in cis_level_1_exclusions"
