---

- name: Updating yum packages
  yum:
    name: '*'
    state: latest

- name: Install Python3
  raw: yum -y install python3

- name: Installing libselinux-python
  yum:
    name: libselinux-python

- name: Install PIP
  raw: yum -y install python3 python3-pip

#- name: Install Ansible?
  #raw: pip3 install ansible

- name: Updating Jinja2
  raw: yum -y install python3-jinja2

- name: Reboot immediately if there was a change.
  shell: "sleep 5 && reboot"
  async: 1
  poll: 0

- name: reset ssh connection to allow user changes to affect ansible user
  ansible.builtin.meta: reset_connection