---

# 1.1.7 Ensure separate partition exists for /var/tmp (Scored)

- name: 1.1.7 - Ensure separate partition exists for /var/tmp (Scored)
  mount:
    name: "{{ item.mountpoint }}"
    state: present
    fstype: "{{item.fstype}}"
    src: "{{item.device}}"
    opts: "{{item.opts}}"
  with_items:
    - "{{ fs_mounts | selectattr('mountpoint', 'equalto', '/var/tmp') | list }}"
  tags:
      - level-1
      - section-1
      - "1.1.10"
      - scored

# 1.1.12 Ensure noexec option set on /var/tmp partition

- name: 1.1.12 - Ensure noexec option set on /var/tmp partition
  mount:
    name: "{{ item.mountpoint }}"
    state: mounted
    fstype: "{{ item.fstype }}"
    src: "{{ item.device }}"
    opts: "{{ item.opts.split(',') | union(['noexec']) | join(',') }}"
  when: item.mountpoint == '/var/tmp'
  with_items: "{{ fs_mounts }}"
  tags:
    - level-1
    - section-1
    - "1.1.12"
    - scored