---

# 1.1.2 Ensure separate partition exists for /tmp (Scored)

- name: 1.1.2 - Ensure the tmp.mount service is enabled for boot time auto-start
  systemd:
    name: tmp.mount
    enabled: yes
    masked: no
  tags:
      - level-1
      - section-1
      - "1.1.2"
      - scored